Support setting allow-nondistributable-artifacts option on Docker daemon
GoogleCloudPlatform/kubernetes-engine-windows-tools pull request #18
Opened 2023-06-10 06:22 UTC by drcapulet

When working with air gapped installations, it's impossible to run Windows images due to the foreign layers. This enables setting the [`--allow-nondistributable-artifacts`](https://docs.docker.com/engine/reference/commandline/dockerd/#allow-push-of-nondistributable-artifacts) option on the Docker daemon to include the repository where the image will be pushed. https://github.com/containerd/containerd/issues/7676 has a more in depth discussion as to some of the rationale.

2023-06-15 23:50 UTC, ibabou requested changes

2023-06-15 23:50 UTC, ibabou commented on gke-windows-builder/builder/builder/gce.go
> +	setupScriptPS1Template = template.Must(template.New("windows-startup-script-ps1").Parse(`
Can we add a test to verify the templetaization of the used startup script? with & without the additional configuration?

2023-06-15 23:52 UTC, ibabou commented
Thanks @drcapulet for contributing the change. It's useful to have the option to disable the layers if needed. But also, can we've a warning printed mentioning that created images are to be used only with air-gapped situations?

2023-06-28 06:37 UTC, drcapulet commented
@ibabou Funny enough, the day I opened this Microsoft [dropped the usage of foreign layers](https://techcommunity.microsoft.com/t5/containers/announcing-removal-of-foreign-layers-from-windows-container/ba-p/3846833), I'm inclined to just close this out? We're now using the existing main without issue.

2023-06-29 17:09 UTC, ibabou commented
@drcapulet Sounds good! Agree, let's then close it in this case. Thanks again!

2023-06-29 17:09 UTC, ibabou commented
Closing the PR.

2023-06-29 17:09 UTC, closed without merging