Support builds on Windows Server 2022
GoogleCloudPlatform/kubernetes-engine-windows-tools pull request #19
Opened 2023-06-30 04:11 UTC by drcapulet

[MicrosoftDockerProvider](https://github.com/OneGet/MicrosoftDockerProvider) is now deprecated per the README, happy to use this install method for all version but at least on my testing 2022 VM I was unable to install Docker via the old method.

2023-06-30 18:12 UTC, ibabou requested changes
Thanks Alex for the contribution!

2023-06-30 18:12 UTC, ibabou commented on gke-windows-builder/builder/builder/gce.go
>  function Install-Docker {
The DockerMsftProvider Provider is cut now, we were planning to make this change very soon (as "*-for-containers" image used for the only currently supported version ltsc2019 will be removed as well, and we'll switch it to regular core that doesn't have Docker pre-installed). But let's not change the map for ltsc2019 now. Thanks for the update here, can we then remove completely the NuGet based installation? We should only install Docker CE in that case if Docker is not available on the base image.

2023-06-30 18:12 UTC, ibabou commented on gke-windows-builder/builder/builder/gce.go
> +		Write-Host "Installing latest Docker EE version"
"latest Docker CE"

2023-06-30 18:12 UTC, ibabou commented on gke-windows-builder/builder/builder/gce.go
> +		Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1" -o install-docker-ce.ps1
Can we move this to a const defined at the top?

2023-08-03 22:15 UTC, drcapulet commented on gke-windows-builder/builder/builder/gce.go
> +		Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1" -o install-docker-ce.ps1
Are you thinking a constant in Go or the Powershell script? Right now there's no interpolation if you mean the former.

2023-08-03 22:15 UTC, drcapulet commented on gke-windows-builder/builder/builder/gce.go
>  function Install-Docker {
A bit confused, are you asking me to nuke the NuGet pieces as part of this PR?

2023-08-15 20:11 UTC, ibabou commented on gke-windows-builder/builder/builder/gce.go
>  function Install-Docker {
Yes

2023-08-15 20:13 UTC, ibabou commented on gke-windows-builder/builder/builder/gce.go
> +		Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1" -o install-docker-ce.ps1
I meant in the powershell code itself.

2023-08-23 13:10 UTC, idofl commented
Duplicate of https://github.com/GoogleCloudPlatform/kubernetes-engine-windows-tools/pull/20

2024-01-12 18:34 UTC, closed without merging