Add a flag to support VM creation without external IP
GoogleCloudPlatform/kubernetes-engine-windows-tools pull request #9
Opened 2022-01-11 12:50 UTC by barp

When working with internal IP in a shared VPC there might not be any reason to create an external IP to the VM.
And since external IP have quotas you can't have too many builds using it.

We can't do it by default when using internal IP since access to external repositories will require Cloud NAT to be enabled and it has costs associated with it.

2022-01-14 01:38 UTC, pjh requested changes
Sorry for the delayed review, just one comment.

2022-01-14 01:38 UTC, pjh commented on gke-windows-builder/builder/main.go
> +	ExternalIP          = flag.Bool("external-ip", true, "Create external IP addresses for VMs, please note that if a builder needs to download a base image from outside of gcr Cloud NAT will have to be
> please note that if a builder needs to download a base image from outside of gcr Cloud NAT will have to be enabled

I don't know if it applies when the flag is true, when the flag is false, or in all cases. Can you clarify?

I'm also wondering, is this the right place for this note? Would it make more sense to emit this as a log message while the builder is running? gke-windows-builder/README.md might also be a good place for this.

2022-01-14 04:47 UTC, barp commented on gke-windows-builder/builder/main.go
> +	ExternalIP          = flag.Bool("external-ip", true, "Create external IP addresses for VMs, please note that if a builder needs to download a base image from outside of gcr Cloud NAT will have to be
when the flag is true.
the readme is a good place. I can add it there.
while the builder is running might be too annoying for a user since the build is gauranteed to fail if he didn't set it up, and windows builds takes a very long time.

2022-01-20 06:27 UTC, barp commented on gke-windows-builder/builder/main.go
> +	ExternalIP          = flag.Bool("external-ip", true, "Create external IP addresses for VMs, please note that if a builder needs to download a base image from outside of gcr Cloud NAT will have to be
Are the changes in the README ok?

2022-01-20 19:14 UTC, pjh commented on gke-windows-builder/builder/main.go
> +	ExternalIP          = flag.Bool("external-ip", true, "Create external IP addresses for VMs, please note that if a builder needs to download a base image from outside of gcr Cloud NAT will have to be
Thanks for the README addition. Can you please still update the flag text to be more clear? I guess something like:

"Create external IP addresses for VMs. If false then Cloud NAT must be enabled, see the README for details."

(Sorry I missed replying last week.)

2022-02-01 06:59 UTC, barp commented
Hi can you take a look again?

2022-02-02 01:26 UTC, pjh commented
LGTM, thanks!

FYI I don't get email notifications when you push a new commit or resolve a comment, please add a comment somewhere when you'd like a re-review.

2022-02-02 01:27 UTC, merged